import type { Product } from "./types";

/**
 * Collection 001 — The Foundations.
 *
 * These are the house's own pieces, taken from the NN brand documents.
 * Price, stock and photography are deliberately null: they are owned by
 * Shopify and appear the moment the Storefront API is connected.
 * Nothing on this page is invented.
 */
export const COLLECTION_001: Product[] = [
  {
    id: "preview:oxford-bianco",
    handle: "the-oxford-bianco",
    title: "The Oxford",
    colour: "Bianco",
    swatch: "#f2efe6",
    category: "shirts",
    fabric: "Cotton oxford",
    fit: "Considered — clean through the body, room to move at the shoulder",
    description:
      "The shirt the wardrobe is built around. Cotton oxford, a soft collar that holds its roll, single-needle side seams and the woven NN label at the back neck.",
    care: [
      "Wash at 30°C on a gentle cycle",
      "Hang to dry away from direct sun",
      "Press warm on the reverse",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    price: null,
    images: [],
    modelGlb: null,
    variants: [],
    preview: true,
    sizeChart: null,
  },
  {
    id: "preview:oxford-azure",
    handle: "the-oxford-azure",
    title: "The Oxford",
    colour: "Azure",
    swatch: "#b9c8d6",
    category: "shirts",
    fabric: "Cotton oxford",
    fit: "Considered — clean through the body, room to move at the shoulder",
    description:
      "The Oxford in a quiet blue. The same collar roll, the same single-needle finish, a colour that carries from morning to evening.",
    care: [
      "Wash at 30°C on a gentle cycle",
      "Hang to dry away from direct sun",
      "Press warm on the reverse",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    price: null,
    images: [],
    modelGlb: null,
    variants: [],
    preview: true,
    sizeChart: null,
  },
  {
    id: "preview:poplin-ecru",
    handle: "the-poplin-ecru",
    title: "The Poplin",
    colour: "Écru",
    swatch: "#e7dfcd",
    category: "shirts",
    fabric: "Cotton poplin",
    fit: "Considered — a closer hand than the oxford, the same shoulder",
    description:
      "A finer, smoother cloth with a cool hand. Poplin holds a crease where the oxford softens it, which is what makes it the evening shirt of the collection.",
    care: ["Wash at 30°C", "Hang to dry", "Press warm while slightly damp"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    price: null,
    images: [],
    modelGlb: null,
    variants: [],
    preview: true,
    sizeChart: null,
  },
  {
    id: "preview:stripe-marine",
    handle: "the-stripe-marine",
    title: "The Stripe",
    colour: "Marine",
    swatch: "#2f4257",
    category: "shirts",
    fabric: "Yarn-dyed cotton",
    fit: "Considered",
    description:
      "A yarn-dyed stripe, woven rather than printed, so the colour runs through the thread and stays true through the life of the shirt.",
    care: ["Wash at 30°C with like colours", "Hang to dry", "Press warm on the reverse"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    price: null,
    images: [],
    modelGlb: null,
    variants: [],
    preview: true,
    sizeChart: null,
  },
  {
    id: "preview:tailored-trouser-sable",
    handle: "the-tailored-trouser-sable",
    title: "The Tailored Trouser",
    colour: "Sable",
    swatch: "#9a8875",
    category: "trousers",
    fabric: "Wool-blend twill",
    fit: "Straight — a clean line from hip to hem",
    description:
      "Cut straight and finished flat at the front. The twill has enough weight to fall without clinging, which is the whole point of a tailored trouser.",
    care: ["Dry clean", "Steam to refresh", "Hang from the waistband"],
    sizes: ["30", "32", "34", "36", "38", "40"],
    price: null,
    images: [],
    modelGlb: null,
    variants: [],
    preview: true,
    sizeChart: null,
  },
  {
    id: "preview:tailored-trouser-charcoal",
    handle: "the-tailored-trouser-charcoal",
    title: "The Tailored Trouser",
    colour: "Charcoal",
    swatch: "#2e2e2e",
    category: "trousers",
    fabric: "Wool-blend twill",
    fit: "Straight — a clean line from hip to hem",
    description:
      "The trouser that goes with everything in the collection. Charcoal reads as black at night and as grey in daylight.",
    care: ["Dry clean", "Steam to refresh", "Hang from the waistband"],
    sizes: ["30", "32", "34", "36", "38", "40"],
    price: null,
    images: [],
    modelGlb: null,
    variants: [],
    preview: true,
    sizeChart: null,
  },
  {
    id: "preview:tailored-trouser-marine",
    handle: "the-tailored-trouser-marine",
    title: "The Tailored Trouser",
    colour: "Marine",
    swatch: "#2b3a4d",
    category: "trousers",
    fabric: "Wool-blend twill",
    fit: "Straight — a clean line from hip to hem",
    description: "Marine sits between navy and slate, and settles the outfit without darkening it.",
    care: ["Dry clean", "Steam to refresh", "Hang from the waistband"],
    sizes: ["30", "32", "34", "36", "38", "40"],
    price: null,
    images: [],
    modelGlb: null,
    variants: [],
    preview: true,
    sizeChart: null,
  },
  {
    id: "preview:pleated-trouser-pierre",
    handle: "the-pleated-trouser-pierre",
    title: "The Pleated Trouser",
    colour: "Pierre",
    swatch: "#b7b1a7",
    category: "trousers",
    fabric: "Wool-blend twill",
    fit: "Relaxed — a single forward pleat, easy through the thigh",
    description:
      "A single forward pleat gives room through the thigh and lets the leg fall straight. Sits higher on the waist than the tailored trouser.",
    care: ["Dry clean", "Steam to refresh", "Hang from the waistband"],
    sizes: ["30", "32", "34", "36", "38", "40"],
    price: null,
    images: [],
    modelGlb: null,
    variants: [],
    preview: true,
    sizeChart: null,
  },
];
